DROP TABLE IF EXISTS TB_USER1;

CREATE TABLE TB_USER1
(
    username  VARCHAR(250) PRIMARY KEY,
    pw  VARCHAR(250) NOT NULL,
    first_name VARCHAR(250) NOT NULL,
    last_name  VARCHAR(250) NOT NULL,
    email     VARCHAR(250) NOT NULL,
    role VARCHAR (250) NOT NULL
);
